// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package v1

import (
	"fmt"
	"strings"
)

const (
	// ComponentTypeUnknown is a ComponentType of type unknown.
	ComponentTypeUnknown ComponentType = "unknown"
	// ComponentTypeTarget is a ComponentType of type target.
	ComponentTypeTarget ComponentType = "target"
	// ComponentTypeScanner is a ComponentType of type scanner.
	ComponentTypeScanner ComponentType = "scanner"
	// ComponentTypeEnricher is a ComponentType of type enricher.
	ComponentTypeEnricher ComponentType = "enricher"
	// ComponentTypeFilter is a ComponentType of type filter.
	ComponentTypeFilter ComponentType = "filter"
	// ComponentTypeReporter is a ComponentType of type reporter.
	ComponentTypeReporter ComponentType = "reporter"
)

var ErrInvalidComponentType = fmt.Errorf("not a valid ComponentType, try [%s]", strings.Join(_ComponentTypeNames, ", "))

var _ComponentTypeNames = []string{
	string(ComponentTypeUnknown),
	string(ComponentTypeTarget),
	string(ComponentTypeScanner),
	string(ComponentTypeEnricher),
	string(ComponentTypeFilter),
	string(ComponentTypeReporter),
}

// ComponentTypeNames returns a list of possible string values of ComponentType.
func ComponentTypeNames() []string {
	tmp := make([]string, len(_ComponentTypeNames))
	copy(tmp, _ComponentTypeNames)
	return tmp
}

// ComponentTypeValues returns a list of the values for ComponentType
func ComponentTypeValues() []ComponentType {
	return []ComponentType{
		ComponentTypeUnknown,
		ComponentTypeTarget,
		ComponentTypeScanner,
		ComponentTypeEnricher,
		ComponentTypeFilter,
		ComponentTypeReporter,
	}
}

// String implements the Stringer interface.
func (x ComponentType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ComponentType) IsValid() bool {
	_, err := ParseComponentType(string(x))
	return err == nil
}

var _ComponentTypeValue = map[string]ComponentType{
	"unknown":  ComponentTypeUnknown,
	"target":   ComponentTypeTarget,
	"scanner":  ComponentTypeScanner,
	"enricher": ComponentTypeEnricher,
	"filter":   ComponentTypeFilter,
	"reporter": ComponentTypeReporter,
}

// ParseComponentType attempts to convert a string to a ComponentType.
func ParseComponentType(name string) (ComponentType, error) {
	if x, ok := _ComponentTypeValue[name]; ok {
		return x, nil
	}
	return ComponentType(""), fmt.Errorf("%s is %w", name, ErrInvalidComponentType)
}
