---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: enricher-codeowners
  labels:
    v1.smithy.smithy-security.com/component: enricher
spec:
  description: Identifies a code owner for each finding.
  params:
  - name: enricher-codeowners-annotation
    type: string
    default: ""

  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-enricher
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/enrichers/codeowners:{{ .Chart.AppVersion }}'
    command: ["/app/components/enrichers/codeowners/codeowners"]
    env:
    - name: READ_PATH
      value: $(workspaces.output.path)/.smithy/producers
    - name: WRITE_PATH
      value: "$(workspaces.output.path)/.smithy/enrichers/codeowners"
    - name: REPO_BASE_PATH
      value: "$(workspaces.output.path)/"
    - name: ANNOTATION
      value: "$(params.enricher-codeowners-annotation)"
