name: trivy-based-image-scanning
description: |
  Trivy based workflow for image scanning. Temporarily uses a git clone component which is not actually used
components:
- component: file://new-components/targets/git-clone/component.yaml
- component: file://new-components/scanners/trivy/component.yaml
- component: file://new-components/enrichers/custom-annotation/component.yaml
- component: file://new-components/reporters/json-logger/component.yaml
