---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: smithy-typescript-project-
  namespace: smithy
spec:
  pipelineRef:
    name: smithy-typescript-project
  params:
  - name: git-clone-url
    # TODO(OCU-154): Switch to smithy-security/e2e-monorepo
    value: https://github.com/appsecco/dvna.git
  workspaces:
  - name: output
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
