---
runner:
  go/vet:
    cmd: go vet $(go list ./... | grep -v vendor | grep -v smithy/deprecated-components | grep -v smithy/api/proto)
    format: govet

  go/staticcheck:
    cmd: staticcheck -checks "all,-SA1019,-ST1000" $(go list ./... | grep -v vendor | grep -v smithy/deprecated-components | grep -v smithy/api/proto)
    format: staticcheck

  go/revive:
    cmd: |
      CONFIG_FILE="$(pwd)/revive.toml" find ./components/ -name go.mod -type f -exec bash -c 'cd $(dirname {}) &&
      revive -exclude ./vendor/... -config ${CONFIG_FILE} ./...' \;
    errorformat:
      - '%f:%l:%c: %m'
 
  go/containedctx:
    cmd: go vet -vettool=$(which containedctx) $(go list ./... | grep -v vendor | grep -v smithy/deprecated-components | grep -v smithy/api/proto)
    errorformat:
      - '%f:%l:%c: %m'

  go/ineffassign:
    cmd: ineffassign $(go list ./... | grep -v vendor | grep -v smithy/deprecated-components | grep -v smithy/api/proto)
    errorformat:
      - '%f:%l:%c: %m'

  go/errorlint:
    cmd: go-errorlint -errorf-multi -errorf -test $(go list ./... | grep -v vendor | grep -v smithy/deprecated-components | grep -v smithy/api/proto)
    errorformat:
      - '%f:%l:%c: %m'

  go/errcheck:
    cmd: errcheck -asserts -blank $(go list ./... | grep -v vendor | grep -v smithy/deprecated-components | grep -v smithy/api/proto)
    errorformat:
      - '%f:%l:%c:%m'

  npm/remark:
    ###################### Removes ansi codes see https://github.com/reviewdog/errorformat/issues/51
    cmd: npm run lint | sed 's/\x1b\[[0-9;]*m//g'
    format: remark-lint

  # TODO: figure out how to set errorformat to parse the error output
  # actionlint:
  #   cmd: actionlint
  #   errorformat:
  #     - 

  # TODO(OCU-130): Enable buf-lint again
  # buf_lint:
  #   cmd: buf lint . --path ./api/
  #   level: error
  #   format: buf
