---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: smithy-python-project-
  namespace: smithy
spec:
  pipelineRef:
    name: smithy-python-project
  params:
  - name: git-clone-url
    value: https://github.com/smithy-security/e2e-monorepo.git
  workspaces:
  - name: output
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
