services:
  enricher:
    build:
      context: ../..
      args:
        - COMPONENT_PATH=enrichers/custom-annotation
        - COMPONENT_BINARY_SOURCE_PATH=cmd/main.go
    platform: linux/amd64
    env_file:
      - .env
