
elasticsearch:
  enabled: true
  version: 8.3.2

kibana:
  enabled: true
  version: 8.3.2
  ingress:
    enabled: true
    className: nginx
    host: kibana.smithy.localhost
    tlsEnabled: false

mongodb:
  enabled: true
  auth:
    enabled: true
    usernames: ["consumer-mongodb"]
    passwords: ["consumer-mongodb"]
    databases: ["consumer-mongodb"]

arangodb:
  enabled: true
  version: 3.7.10
  ingress:
    className: nginx
    host: arangodb.smithy.localhost

image:
  registry: kind-registry:5000/smithy-security/smithy

database: &psqlConfig
  host: smithy-postgresql:5432
  auth:
    username: smithy
    password: smithy
    database: smithy
    postgresPassword: smithy
    querystringargs: "sslmode=disable"

postgresql:
  enabled: true
  <<: *psqlConfig

tekton:
  enabled: true

deduplication-db-migrations:
  enabled: true
  database: *psqlConfig
