---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: smithy-sca-project-
  namespace: smithy
spec:
  pipelineRef:
    name: smithy-sca-project
  params:
  - name: producer-docker-trivy-target
    value: python:3.4-alpine
  workspaces:
  - name: output
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
