---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -yarn-audit-purl-project
components:
  - pkg:helm/smithy-security-oss-components/base
  - pkg:helm/smithy-security-oss-components/source-dependency
  - pkg:helm/smithy-security-oss-components/producer-typescript-yarn-audit
  - pkg:helm/smithy-security-oss-components/producer-aggregator
  - pkg:helm/smithy-security-oss-components/enricher-deduplication
  - pkg:helm/smithy-security-oss-components/enricher-aggregator
  - pkg:helm/smithy-security-oss-components/consumer-mongodb
