---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-typescript-eslint
  labels:
    v1.smithy.smithy-security.com/component: producer
    v1.smithy.smithy-security.com/test-type: sast
    v1.smithy.smithy-security.com/language: typescript
    v1.smithy.smithy.security/component/maturity: experimental
spec:
  description: Static analysis for javascript and typescript projects.
  params:
    - name: producer-typescript-eslint-config-js
      type: string
      default: ""
  volumes:
  - name: scratch
    emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-eslint
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/producers/typescript-eslint/eslint-wrapper:{{ .Chart.AppVersion }}'
    command: ["/home/node/workspace/eslint-wrapper"]
    args:
     - -t
     - $(workspaces.output.path)
     - -c
     - "$(params.producer-typescript-eslint-config-js)"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
  - name: produce-issues
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/producers/typescript-eslint:{{ .Chart.AppVersion }}'
    command: ["/app/components/producers/typescript-eslint/typescript-eslint-parser"]
    args:
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.output.path)/.smithy/producers/typescript-eslint.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
