description: MobSFScan based workflow
name: mobsfscan
components:
- component: file://components/targets/git-clone/component.yaml
- component: file://components/scanners/mobsfscan/component.yaml
- component: file://components/enrichers/custom-annotation/component.yaml
- component: file://components/reporters/battlecard-printer/component.yaml
