description: GoSec based workflow
name: gosec
components:
- component: file://components/targets/git-clone/component.yaml
- component: file://components/scanners/gosec/component.yaml
- component: file://components/scanners/nancy/component.yaml
- component: file://components/enrichers/custom-annotation/component.yaml
- component: file://components/filters/severity/component.yaml
- component: file://components/reporters/json-logger/component.yaml
