// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package component

import (
	"errors"
	"fmt"
)

const (
	// RunnerConfigLoggingLevelDebug is a RunnerConfigLoggingLevel of type debug.
	RunnerConfigLoggingLevelDebug RunnerConfigLoggingLevel = "debug"
	// RunnerConfigLoggingLevelInfo is a RunnerConfigLoggingLevel of type info.
	RunnerConfigLoggingLevelInfo RunnerConfigLoggingLevel = "info"
	// RunnerConfigLoggingLevelError is a RunnerConfigLoggingLevel of type error.
	RunnerConfigLoggingLevelError RunnerConfigLoggingLevel = "error"
	// RunnerConfigLoggingLevelWarn is a RunnerConfigLoggingLevel of type warn.
	RunnerConfigLoggingLevelWarn RunnerConfigLoggingLevel = "warn"
)

var ErrInvalidRunnerConfigLoggingLevel = errors.New("not a valid RunnerConfigLoggingLevel")

// String implements the Stringer interface.
func (x RunnerConfigLoggingLevel) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RunnerConfigLoggingLevel) IsValid() bool {
	_, err := ParseRunnerConfigLoggingLevel(string(x))
	return err == nil
}

var _RunnerConfigLoggingLevelValue = map[string]RunnerConfigLoggingLevel{
	"debug": RunnerConfigLoggingLevelDebug,
	"info":  RunnerConfigLoggingLevelInfo,
	"error": RunnerConfigLoggingLevelError,
	"warn":  RunnerConfigLoggingLevelWarn,
}

// ParseRunnerConfigLoggingLevel attempts to convert a string to a RunnerConfigLoggingLevel.
func ParseRunnerConfigLoggingLevel(name string) (RunnerConfigLoggingLevel, error) {
	if x, ok := _RunnerConfigLoggingLevelValue[name]; ok {
		return x, nil
	}
	return RunnerConfigLoggingLevel(""), fmt.Errorf("%s is %w", name, ErrInvalidRunnerConfigLoggingLevel)
}

const (
	// LocalStoreColumnNameFindings is a localStoreColumnName of type findings.
	LocalStoreColumnNameFindings localStoreColumnName = "findings"
	// LocalStoreColumnNameInstanceId is a localStoreColumnName of type instance_id.
	LocalStoreColumnNameInstanceId localStoreColumnName = "instance_id"
	// LocalStoreColumnNameUpdatedAt is a localStoreColumnName of type updated_at.
	LocalStoreColumnNameUpdatedAt localStoreColumnName = "updated_at"
)

var ErrInvalidlocalStoreColumnName = errors.New("not a valid localStoreColumnName")

// String implements the Stringer interface.
func (x localStoreColumnName) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x localStoreColumnName) IsValid() bool {
	_, err := ParselocalStoreColumnName(string(x))
	return err == nil
}

var _localStoreColumnNameValue = map[string]localStoreColumnName{
	"findings":    LocalStoreColumnNameFindings,
	"instance_id": LocalStoreColumnNameInstanceId,
	"updated_at":  LocalStoreColumnNameUpdatedAt,
}

// ParselocalStoreColumnName attempts to convert a string to a localStoreColumnName.
func ParselocalStoreColumnName(name string) (localStoreColumnName, error) {
	if x, ok := _localStoreColumnNameValue[name]; ok {
		return x, nil
	}
	return localStoreColumnName(""), fmt.Errorf("%s is %w", name, ErrInvalidlocalStoreColumnName)
}
