# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: findings_service/v1/findings_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'findings_service/v1/findings_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ocsf_schema.v1 import ocsf_schema_pb2 as ocsf__schema_dot_v1_dot_ocsf__schema__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*findings_service/v1/findings_service.proto\x12\x13\x66indings_service.v1\x1a ocsf_schema/v1/ocsf_schema.proto\"Y\n\x07\x46inding\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12>\n\x07\x64\x65tails\x18\x02 \x01(\x0b\x32$.ocsf_schema.v1.VulnerabilityFindingR\x07\x64\x65tails\"v\n\x12GetFindingsRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n\x04page\x18\x02 \x01(\rH\x00R\x04page\x88\x01\x01\x12 \n\tpage_size\x18\x03 \x01(\rH\x01R\x08pageSize\x88\x01\x01\x42\x07\n\x05_pageB\x0c\n\n_page_size\"O\n\x13GetFindingsResponse\x12\x38\n\x08\x66indings\x18\x01 \x03(\x0b\x32\x1c.findings_service.v1.FindingR\x08\x66indings\"a\n\x15UpdateFindingsRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x38\n\x08\x66indings\x18\x02 \x03(\x0b\x32\x1c.findings_service.v1.FindingR\x08\x66indings\"\x18\n\x16UpdateFindingsResponse\"i\n\x15\x43reateFindingsRequest\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12@\n\x08\x66indings\x18\x02 \x03(\x0b\x32$.ocsf_schema.v1.VulnerabilityFindingR\x08\x66indings\"\x18\n\x16\x43reateFindingsResponse2\xc9\x02\n\x0f\x46indingsService\x12`\n\x0bGetFindings\x12\'.findings_service.v1.GetFindingsRequest\x1a(.findings_service.v1.GetFindingsResponse\x12i\n\x0eUpdateFindings\x12*.findings_service.v1.UpdateFindingsRequest\x1a+.findings_service.v1.UpdateFindingsResponse\x12i\n\x0e\x43reateFindings\x12*.findings_service.v1.CreateFindingsRequest\x1a+.findings_service.v1.CreateFindingsResponseB?Z=github.com/smithy-security/smithy/sdk/gen/findings_service/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'findings_service.v1.findings_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/smithy-security/smithy/sdk/gen/findings_service/v1'
  _globals['_FINDING']._serialized_start=101
  _globals['_FINDING']._serialized_end=190
  _globals['_GETFINDINGSREQUEST']._serialized_start=192
  _globals['_GETFINDINGSREQUEST']._serialized_end=310
  _globals['_GETFINDINGSRESPONSE']._serialized_start=312
  _globals['_GETFINDINGSRESPONSE']._serialized_end=391
  _globals['_UPDATEFINDINGSREQUEST']._serialized_start=393
  _globals['_UPDATEFINDINGSREQUEST']._serialized_end=490
  _globals['_UPDATEFINDINGSRESPONSE']._serialized_start=492
  _globals['_UPDATEFINDINGSRESPONSE']._serialized_end=516
  _globals['_CREATEFINDINGSREQUEST']._serialized_start=518
  _globals['_CREATEFINDINGSREQUEST']._serialized_end=623
  _globals['_CREATEFINDINGSRESPONSE']._serialized_start=625
  _globals['_CREATEFINDINGSRESPONSE']._serialized_end=649
  _globals['_FINDINGSSERVICE']._serialized_start=652
  _globals['_FINDINGSSERVICE']._serialized_end=981
# @@protoc_insertion_point(module_scope)
