---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-cdxgen
  labels:
    v1.smithy.smithy-security.com/component: producer
    v1.smithy.smithy-security.com/test-type: sbom
    v1.smithy.smithy-security.com/language: all
    v1.smithy.smithy.security/component/maturity: experimental
spec:
  description: Generate a CycloneDX SBOM from source code.
  params:
    - name: producer-cdxgen-flags
      type: array
      default: []
    - name: producer-cdxgen-fetch-license
      type: string
      default: "false"
    - name: producer-cdxgen-github-token
      type: string
      default: ""
    - name: producer-cdxgen-astgen-ignore-file-pattern
      type: string
      default: ""
    - name: producer-cdxgen-astgen-ignore-dirs
      type: string
      default: ""
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
    - name: run-cdxgen
      image: ghcr.io/cyclonedx/cdxgen:v10.9.5
      env:
        - name: FETCH_LICENSE
          value: $(params.producer-cdxgen-fetch-license)
        - name: GITHUB_TOKEN
          value: $(params.producer-cdxgen-github-token)
        - name: ASTGEN_IGNORE_FILE_PATTERN
          value: $(params.producer-cdxgen-astgen-ignore-file-pattern)
        - name: ASTGEN_IGNORE_DIRS
          value: $(params.producer-cdxgen-astgen-ignore-dirs)
      command:
        - node
      args:
        - /opt/cdxgen/bin/cdxgen.js
        - -r
        - -p
        - -o
        - /scratch/out.json
        - $(workspaces.output.path)/
        - --spec-version
        - "1.5"
      volumeMounts:
        - mountPath: /scratch
          name: scratch

    - name: produce-issues
      imagePullPolicy: IfNotPresent
      image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/producers/cdxgen:{{ .Chart.AppVersion }}'
      command: ["/app/components/producers/cdxgen/cdxgen-parser"]
      args:
        - "-in=/scratch/out.json"
        - "-out=$(workspaces.output.path)/.smithy/producers/cdxgen.pb"
      volumeMounts:
        - mountPath: /scratch
          name: scratch
