---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: smithy-iac-project-
  namespace: smithy
spec:
  pipelineRef:
    name: smithy-iac-project
  params:
  - name: repository_url
    value: https://github.com/smithy-security/e2e-monorepo.git
  - name: producer-docker-trivy-target
    value: "ubuntu:latest"
  - name: producer-docker-trivy-format
    value: sarif
  - name: producer-docker-trivy-command
    value: image
  - name: b64-signature-key
  # THIS IS AN EXAMPLE, PLEASE USE A PROPERLY SECURED SECRET KEY IN PRODUCTION
  # Corresponding public key for verification is MOt7TFuLyGB9yRN5mcIeAPa6jKoFglkwEwGBTOVLeXI=
    value: Lvbo+wAsW8Y4ENBA+lAikOwGTYAIXCQ49eRMEwClv94w63tMW4vIYH3JE3mZwh4A9rqMqgWCWTATAYFM5Ut5cg==  
  workspaces:
  - name: output
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
