---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -rails-project
components:
  - pkg:helm/smithy-security-oss-components/base
  - pkg:helm/smithy-security-oss-components/git-clone
  - components/producers/brakeman
  - pkg:helm/smithy-security-oss-components/producer-aggregator
  - pkg:helm/smithy-security-oss-components/enricher-codeowners
  - pkg:helm/smithy-security-oss-components/enricher-aggregator
  - pkg:helm/smithy-security-oss-components/consumer-elasticsearch
