---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: smithy-rails-project-
spec:
  pipelineRef:
    name: smithy-rails-project
  params:
  - name: git-clone-url
    value: https://github.com/guilleiguaran/dvra
  - name: git-clone-subdirectory
    value: source-code
  workspaces:
  - name: output
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
