---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-brakeman
  labels:
    v1.smithy.smithy-security.com/component: producer
    v1.smithy.smithy-security.com/test-type: sast
    v1.smithy.smithy-security.com/language: brakeman
spec:
  description: Analyse Ruby source code usign brakeman to look for security issues.
  params:
  - name: producer-brakeman-flags
    type: array
    default:
    - "--run-all-checks"
    - "--skip-libs"
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-brakeman
    image: presidentbeef/brakeman:v6.2.1.1
    command: [/usr/src/app/bin/brakeman]
    args:
    - "$(params.producer-brakeman-flags[*])"
    - "--format"
    - "json"
    - "--force-scan"
    - "--output"
    - "/scratch/out.json"
    - "-q"
    - "--path"
    - "$(workspaces.output.path)/source-code/"
    - "--no-exit-on-error"
    - "--no-exit-on-warn"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/producers/brakeman:{{ .Chart.AppVersion }}'
    command: ["/app/components/producers/brakeman/brakeman-parser"]
    args:
    - "-in=/scratch/out.json"
    - "-out=$(workspaces.output.path)/.smithy/producers/brakeman.pb"
    volumeMounts:
    - mountPath: /scratch
      name: scratch
