---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: enricher-deduplication
  labels:
    v1.smithy.smithy-security.com/component: enricher
    v1.smithy.smithy.security/component/maturity: experimental
spec:
  description: Compares multiple inputs and removes duplicates.
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-enricher
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/enrichers/deduplication:{{ .Chart.AppVersion }}'
    command: ["/app/components/enrichers/deduplication/deduplication"]
    env:
    - name: READ_PATH
      value: $(workspaces.output.path)/.smithy/producers
    - name: WRITE_PATH
      value: $(workspaces.output.path)/.smithy/enrichers/deduplication
    - name: DB_CONNECTION
      value: postgresql://{{.Values.database.auth.username}}:{{.Values.database.auth.password}}@{{.Values.database.host}}/{{.Values.database.auth.database}}?{{.Values.database.auth.querystringargs}}
