---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-golang-gosec
  labels:
    v1.smithy.smithy-security.com/component: producer
    v1.smithy.smithy-security.com/test-type: sast
    v1.smithy.smithy-security.com/language: golang
spec:
  description: Analyse Go source code to look for security issues.
  params:
  - name: producer-golang-gosec-flags
    type: array
    default:
    - "-r"
    - "-sort"
    - "-nosec"
  steps:
  - name: run-gosec
    image: docker.io/securego/gosec:2.15.0
    command: [gosec]
    args:
    - "$(params.producer-golang-gosec-flags[*])"
    - "-fmt=json"
    - "-out=$(workspaces.scratch.path)/out.json"
    - "-no-fail"
    - "$(workspaces.source-code.path)/..."
  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/producers/golang-gosec:{{ .Chart.AppVersion }}'
    command: ["/app/components/producers/golang-gosec/golang-gosec-parser"]
    args:
    - "-in=$(workspaces.scratch.path)/out.json"
    - "-out=$(workspaces.scratch.path)/golang-gosec.pb"
