---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-aggregator
  labels:
    v1.smithy.smithy-security.com/component: producer-aggregator
spec:
  description: Combines multiple inputs into a single one.
  params: []
  results: []
  steps:
  - name: aggregate
    image: docker.io/busybox
    command: ["ls"]
    args: ["$(workspaces.source-code.path)"]
    env: []
  - name: tag
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/producers/tagger:{{ .Chart.AppVersion }}'
    command: ["/app/components/producers/aggregator/tagger"]
    env:
    - name: READ_PATH
      value: $(workspaces.scratch.path)
    - name: WRITE_PATH
      value: "$(workspaces.scratch.path)"
