---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-python-bandit
  labels:
    v1.smithy.smithy-security.com/component: producer
    v1.smithy.smithy-security.com/test-type: sast
    v1.smithy.smithy-security.com/language: python
spec:
  description: SAST scanner that analyses Python source code to look for security issues.
  volumes:
  - name: scratch
    emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-bandit
    imagePullPolicy: IfNotPresent
    image: 'python:3.10-slim'
    script: |
      pip3 install bandit
      bandit \
        --recursive \
        $(workspaces.source-code.path) \
        --format json \
        --output $(workspaces.scratch.path)/out.json \
        || true
      cat $(workspaces.scratch.path)/out.json
  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/producers/python-bandit:{{ .Chart.AppVersion }}'
    command: ["/app/components/producers/python-bandit/python-bandit-parser"]
    args:
    - "-in=$(workspaces.scratch.path)/out.json"
    - "-out=$(workspaces.scratch.path)/python-bandit.pb"
