services:
  reporter:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - COMPONENT_PATH=reporters/pdf
        - COMPONENT_BINARY_SOURCE_PATH=cmd/main.go
    platform: linux/amd64
    env_file:
      - .env
