---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: consumer-arangodb
  labels:
    v1.smithy.smithy-security.com/component: consumer
spec:
  description: Pushes findings to an ArangoDB database.
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-consumer
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/consumers/arangodb:{{ .Chart.AppVersion }}'
    command: ["/app/components/consumers/arangodb/arangodb"]
    args: [
      "-in", "$(workspaces.output.path)/.smithy/enrichers/",
      "-db-url", "https://smithy.arangodb.svc:8529",
      "-db-name", "smithy",
      "-collection-name", "smithy",
      "-basic-auth-user", "",
      "-basic-auth-pass", "",
      "-tls-insecure-skip-verify",
    ]
