---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: enricher-reachability
  labels:
    v1.smithy.smithy-security.com/component: enricher
spec:
  description: Performs a reachability check on a supplied repository using AppThreat/atom.
  params:
    - name: enricher-reachability-programming-language
      type: string
  steps:
  - name: run-cdxgen
    image: ghcr.io/cyclonedx/cdxgen:v11.1.0
    command:
      - node
    env:
      - name: NPM_INSTALL_ARGS
        value: "--force --ignore-scripts --package-lock --legacy-peer-deps"
    args:
      - /opt/cdxgen/bin/cdxgen.js
      - -t
      - $(params.enricher-reachability-programming-language)
      - --deep
      - -r
      - --feature-flags safe-pip-install
      - -p
      - -o
      - $(workspaces.source-code.path)/bom.json
      - $(workspaces.source-code.path)
      - --spec-version
      - "1.5"
  - name: run-atom
    imagePullPolicy: IfNotPresent
    image: ghcr.io/appthreat/atom:v2.0.18@sha256:893ed9ede9eea19540027faf72aa618e2b488192378f590fd2a1277b77712c1a
    command:
      - /bin/sh
      - -c
      - atom reachables -o $(workspaces.source-code.path)/app.atom -s $(workspaces.scratch.path)/reachables.json -l $(params.enricher-reachability-programming-language) $(workspaces.source-code.path)
  - name: run-enricher
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/enrichers/reachability:{{ .Chart.AppVersion }}'
    command: ["/app/components/enrichers/reachability/reachability"]
    env:
    - name: READ_PATH
      value: $(workspaces.scratch.path)
    - name: WRITE_PATH
      value: $(workspaces.scratch.path)/reachability
    - name: ATOM_FILE_PATH
      value: $(workspaces.scratch.path)/reachables.json
