description: GoSec based workflow
name: gosec
components:
- component: file://new-components/targets/git-clone/component.yaml
- component: file://new-components/scanners/semgrep/component.yaml
- component: file://new-components/enrichers/custom-annotation/component.yaml
- component: file://new-components/reporters/json-logger/component.yaml
