---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: smithy-ghas-project-
  namespace: smithy
spec:
  pipelineRef:
    name: smithy-ghas-project
  params:
  - name: git-clone-url
    value: https://github.com/smithy-security/e2e-monorepo.git
  - name: producer-github-codeql-repository-owner
    value: smithy-security
  - name: producer-github-codeql-repository-name
    value: e2e-monorepo
  # Insert your GitHub Personal Access Token (PAT) here
  # Note: Must have "Code scanning alerts" repository permissions (read).
  - name: producer-github-codeql-github-token
    value: $github_pat_permissions_to_read_alerts_and_repos
  - name: producer-github-dependabot-repository-owner
    value: smithy-security
  - name: producer-github-dependabot-repository-name
    value: e2e-monorepo
  - name: producer-github-dependabot-github-token
    value: $github_pat_permissions_to_read_alerts_and_repos
  - name: enricher-custom-annotation-base-annotation
    value: '{"foo":"bar","a":"b","1":"2"}'
  workspaces:
  - name: output
    subPath: source-code
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
