description: Nancy based workflow
name: nancy
components:
- component: file://new-components/scanners/zaproxy/component.yaml
- component: file://new-components/enrichers/custom-annotation/component.yaml
- component: file://new-components/reporters/json-logger/component.yaml
