---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: producer-example-tool
  labels:
    v1.smithy.smithy-security.com/component: producer
spec:
  params:
  - name: producer-golang-example-tool
    type: array
    default:
    - "-r"
    - "-quiet"
    - "-sort"
    - "-nosec"
  volumes:
    - name: scratch
      emptyDir: {}
  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: run-example-tool
    image: docker.io/example/tool:2.15.0
    command: [toolcommand]
    args:
    - "$(params.producer-example-tool-flags[*])"
    - "-fmt=json"
    - "-out=$(workspaces.scratch.path)/out.json"
    - "-no-fail"
    - "$(workspaces.source-code.path)/..."
  - name: produce-issues
    imagePullPolicy: IfNotPresent
    image: {{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/producers/example-tool:{{ .Chart.AppVersion }}
    command: ["/app/components/producers/example-tool/example-tool-parser"]
    args:
    - "-in=$(workspaces.scratch.path)/out.json"
    - "-out=$(workspaces.scratch.path)/example-tool.pb"
