description: Reachability based workflow
name: nancy
components:
- component: file://components/targets/git-clone/component.yaml
- component: file://components/scanners/bandit/component.yaml
- component: file://components/enrichers/reachability/component.yaml
- component: file://components/reporters/json-logger/component.yaml
