{{ if .Values.arangodb.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "smithy.fullname" . }}-arangodb
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
  labels:
    {{- include "smithy.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.arangodb.ingress.className }}
  defaultBackend:
    service:
      name: {{ include "smithy.fullname" . }}
      port:
        name: server
  rules:
  - host: {{ .Values.arangodb.ingress.host }}
  {{- if .Values.arangodb.ingress.tlsEnabled }}
  tls:
  - hosts:
    - {{ .Values.arangodb.ingress.host }}
    secretName: cert-kibana
  {{- end }}
{{ end }}
