services:
  scanner:
    build:
      context: ../..
      args:
        - COMPONENT_PATH=scanners/bandit
        - COMPONENT_BINARY_SOURCE_PATH=cmd/main.go
    platform: linux/amd64
    volumes:
      - ./internal/transformer/testdata:/workspace
    env_file:
      - .env
