---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: consumer-jira
  labels:
    v1.smithy.smithy-security.com/component: consumer
spec:
  description: |
   Pushes findings to a Jira instance.
   The Project Name parameter needs to match the project name on Jira
   The Issue Type parameter needs to match the exact issue type of the project on Jira.
   Jira does not support multiple issue types per board.
   Keep in mind that you need to provide both the api token and the email of the user who owns the api token for this component to authenticate.
  volumes:
  - name: scratch
    emptyDir: {}
  params:
    - name: consumer-jira-url
      type: string
    - name: consumer-jira-api-token
      type: string
    - name: consumer-jira-user
      type: string
    - name: consumer-jira-project-name
      type: string
      default: ""
    - name: consumer-jira-issue-type
      type: string
      default: "Task"

  workspaces:
    - name: output
      description: The workspace containing the source-code to scan.
  steps:
  - name: store-config # TODO(spyros): this needs to be a configmap
    imagePullPolicy: IfNotPresent
    image: docker.io/busybox:1.35.0
    script: |
      mkdir -p $(workspaces.output.path)/.smithy/consumers/jira
      cat <<'EOF' > $(workspaces.output.path)/.smithy/consumers/jira/config.json
       {
      "defaultValues": {
          "project": "$(params.consumer-jira-project-name)",
          "issueType": "$(params.consumer-jira-issue-type)",
          "customFields": null
      },
      "descriptionTemplate": "",
      "mappings": null
      }
      EOF
      cat $(workspaces.output.path)/.smithy/consumers/jira/config.json
  - name: run-consumer
    imagePullPolicy: IfNotPresent
    image: '{{ default "ghcr.io/smithy-security/smithy" .Values.image.registry }}/components/consumers/jira:{{ .Chart.AppVersion }}'
    command: ["/app/components/consumers/jira/jira"]
    env:
    - name: SMITHY_JIRA_TOKEN
      value: $(params.consumer-jira-api-token)
    - name: SMITHY_JIRA_USER
      value: $(params.consumer-jira-user)
    - name: SMITHY_JIRA_URL
      value: $(params.consumer-jira-url)
    - name: SMITHY_JIRA_CONFIG_PATH
      value: $(workspaces.output.path)/.smithy/consumers/jira/config.json
    args: [
      "-in",
      "$(workspaces.output.path)/.smithy/enrichers/",
      "-severity-threshold",
       "0"
    ]
