// Code generated by MockGen. DO NOT EDIT.
// Source: internal/images/docker/resolver.go
//
// Generated by this command:
//
//	mockgen -package docker -source internal/images/docker/resolver.go -destination internal/images/docker/docker_puller_mock.go
//

// Package docker is a generated GoMock package.
package docker

import (
	context "context"
	io "io"
	reflect "reflect"

	image "github.com/docker/docker/api/types/image"
	gomock "go.uber.org/mock/gomock"
)

// MockdockerPuller is a mock of dockerPuller interface.
type MockdockerPuller struct {
	ctrl     *gomock.Controller
	recorder *MockdockerPullerMockRecorder
	isgomock struct{}
}

// MockdockerPullerMockRecorder is the mock recorder for MockdockerPuller.
type MockdockerPullerMockRecorder struct {
	mock *MockdockerPuller
}

// NewMockdockerPuller creates a new mock instance.
func NewMockdockerPuller(ctrl *gomock.Controller) *MockdockerPuller {
	mock := &MockdockerPuller{ctrl: ctrl}
	mock.recorder = &MockdockerPullerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdockerPuller) EXPECT() *MockdockerPullerMockRecorder {
	return m.recorder
}

// ImagePull mocks base method.
func (m *MockdockerPuller) ImagePull(ctx context.Context, refStr string, options image.PullOptions) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImagePull", ctx, refStr, options)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ImagePull indicates an expected call of ImagePull.
func (mr *MockdockerPullerMockRecorder) ImagePull(ctx, refStr, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImagePull", reflect.TypeOf((*MockdockerPuller)(nil).ImagePull), ctx, refStr, options)
}
