name: Build component image and package
run-name: Build ${{ github.ref_name }}

on:
  push:
    tags:
      # Matches: components/scanners/gosec/v1.0.0 or components/scanners/gosec/v1.0.0-alpha3 for example.
      - 'components/targets/*/v[0-9].[0-9].[0-9]*'
      - 'components/scanners/*/v[0-9].[0-9].[0-9]*'
      - 'components/enrichers/*/v[0-9].[0-9].[0-9]*'
      - 'components/filters/*/v[0-9].[0-9].[0-9]*'
      - 'components/reporters/*/v[0-9].[0-9].[0-9]*'

permissions:
  # Grant the ability to checkout the repository
  contents: read
  packages: write

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Extract tag details
        id: tag_info
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          COMPONENT_TYPE=$(echo ${TAG} | cut -d/ -f2)
          COMPONENT_NAME=$(echo ${TAG} | cut -d/ -f3)
          COMPONENT_DIR=$(dirname ${TAG})
          VERSION=$(echo ${TAG} | cut -d/ -f4)

          echo "component_type=${COMPONENT_TYPE}" >> ${GITHUB_OUTPUT}
          echo "component_name=${COMPONENT_NAME}" >> ${GITHUB_OUTPUT}
          echo "version=${VERSION}" >> ${GITHUB_OUTPUT}
          echo "tag=${TAG}" >> ${GITHUB_OUTPUT}
          echo "component_dir=${COMPONENT_DIR}" >> ${GITHUB_OUTPUT}

      - name: Extract SDK Version
        id: sdk_version
        run: |
          set -ex
          git tag -l | sort -Vr | head -n 30
          echo "showing tags"
          SDK_VERSION=$(make COMPONENT_DIR=${{ steps.tag_info.outputs.component_dir }} component-sdk-version)
          echo "sdk_version=${SDK_VERSION}" >> ${GITHUB_OUTPUT}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: smithyctl/go.mod

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build CLI, component images and package
        run: |
          set -ex
          make smithyctl/bin
          ./bin/smithyctl/cmd/linux/amd64/smithyctl \
            --debug-enabled=true \
            --debug-level=debug \
            component \
              build \
                --sdk-version=${{ steps.sdk_version.outputs.sdk_version }} \
                --tag=${{ steps.tag_info.outputs.version }} \
                --push \
                "${{ steps.tag_info.outputs.component_dir }}/component.yaml"

          ./bin/smithyctl/cmd/linux/amd64/smithyctl \
            --debug-enabled=true \
            --debug-level=debug \
            component \
              package \
                --sdk-version=${{ steps.sdk_version.outputs.sdk_version }} \
                --version=${{ steps.tag_info.outputs.version }} \
                "${{ steps.tag_info.outputs.component_dir }}/component.yaml"

      - name: Trigger repackaging event in SAAS
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SAAS_TRIGGER_PAT }}
          repository: smithy-security/saas
          event-type: package_published
          client-payload: |- 
            {
              "registry": "ghcr.io",
              "repo_namespace": "smithy-security/smithy/manifests",
              "component_tag": "${{ steps.tag_info.outputs.tag }}"
            }
